apiVersion: v1
kind: Service
metadata:
  name: postgres-container
  namespace: exam
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: exam
spec:
  serviceName: "postgres-container"  # Matches the Service name
  replicas: 1  # Single replica for the database
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: amineleny3/postgres:latest  # Updated image
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: db-password
            - name: POSTGRES_DB
              value: "student_db"  # Create the database named "student_db"
          ports:
            - containerPort: 5432