apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: exam
type: Opaque
data:
  db-user: cG9zdGdyZXM=  # base64 encoded user (e.g. 'postgres')
  db-password: YW1pbmUxMjM=  # base64 encoded password (e.g. 'amine123')
