apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-admin
  namespace: exam
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
