apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-admin-binding
  namespace: exam
subjects:
  - kind: ServiceAccount
    name: default
    namespace: exam
roleRef:
  kind: Role
  name: app-admin
  apiGroup: rbac.authorization.k8s.io
